export const GAME_WIDTH = 800;
export const GAME_HEIGHT = 600;
export const ROAD_HEIGHT = 100;
export const PERSON_RADIUS = 4;
export const PERSON_NUMBER = 10;
export const WALL_Y = GAME_HEIGHT - ROAD_HEIGHT - 8;
export const WALL_HEIGHT = 8;
export const HOLE_WIDTH = 20;
export const HOLE_HEIGHT = WALL_HEIGHT;
export const ORDER_TIME = 3000; // 3 secondi per ordinare
export const HOLE_REVISIT_COOLDOWN = 15000; // 15 seconds in milliseconds
export const PERSONAL_SPACE = PERSON_RADIUS * 2.5; // Spazio minimo tra pedoni
export const AVOIDANCE_FORCE = 15000; // Forza di repulsione
export const ORDERING_REPULSION_FORCE = AVOIDANCE_FORCE * 2; // Forza di repulsione più forte per chi sta ordinando
export const ORDERING_PERSONAL_SPACE = PERSONAL_SPACE * 1.5; // Spazio personale maggiore per chi sta ordinando
export const VERTICAL_MOVEMENT_FACTOR = 0.3; // 30% della velocità orizzontale
export const TARGET_FPS = 30;
export const FRAME_TIME = 1000 / TARGET_FPS; // tempo in ms per frame
